name: btc_app1
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+3
  path: ^1.8.1
  image_picker: ^0.8.7+3
  path_provider: ^2.0.12
  file_picker: ^5.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/default_profile.png
    - assets/images/comic1.jpg
    - assets/images/comic2.jpg
    - assets/images/novel1.jpg
    - assets/images/novel2.jpg

